services:
  # API GATEWAY
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    region: oregon
    dockerContext: backend/apps/api-gateway
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: GITHUB_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://frontend-notifications.onrender.com
      - key: AUTH_SERVICE_HOST
        value: auth-service-8x2f.onrender.com
      - key: AUTH_SERVICE_PORT
        value: 3001
      - key: CONTACTS_SERVICE_HOST
        value: contacts-service-ar6l.onrender.com
      - key: CONTACTS_SERVICE_PORT
        value: 3002
      - key: NOTIFICATIONS_SERVICE_HOST
        value: notifications-service-ztv5.onrender.com
      - key: NOTIFICATIONS_SERVICE_PORT
        value: 3003

  # AUTH SERVICE
  - type: web
    name: auth-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: backend/apps/auth
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

  # CONTACTS SERVICE
  - type: web
    name: contacts-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: backend/apps/contacts
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

  # NOTIFICATIONS SERVICE
  - type: web
    name: notifications-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: backend/apps/notifications
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

  # FRONTEND
  - type: web
    name: frontend-notifications
    runtime: docker
    plan: free
    region: oregon
    dockerContext: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: notifications-db
    plan: free
    region: oregon
