services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: "123456"
      DATABASE_URL: "postgresql://postgres:123456@postgres-db:5432/postgres?schema=public"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notifications-shared-network

  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: ./Dockerfile
      secrets:
        - npmrc
    container_name: api-gateway
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - auth-service
      - contacts-service
      - notifications-service
      - postgres-db
    networks:
      - notifications-shared-network

  auth-service:
    build:
      context: ./apps/auth
      dockerfile: ./Dockerfile
      secrets:
        - npmrc
    container_name: auth-service
    env_file: .env
    depends_on:
      - postgres-db
    networks:
      - notifications-shared-network

  contacts-service:
    build:
      context: ./apps/contacts
      dockerfile: ./Dockerfile
      secrets:
        - npmrc
    container_name: contacts-service
    env_file: .env
    depends_on:
      - postgres-db
    networks:
      - notifications-shared-network

  notifications-service:
    build:
      context: ./apps/notifications
      dockerfile: ./Dockerfile
      secrets:
        - npmrc
    container_name: notifications-service
    env_file: .env
    depends_on:
      - postgres-db
    networks:
      - notifications-shared-network

networks:
  notifications-shared-network:
    external: true
    name: notifications-shared-network
    driver: bridge

volumes:
  postgres_data:

secrets:
  npmrc:
    file: .npmrc
