services:
  # API GATEWAY
  - type: web
    name: api-gateway
    runtime: docker
    repo: https://github.com/margazm/notifications
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: apps/api-gateway/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-bd
          property: connectionString
      - key: AUTH_SERVICE_URL
        value: http://auth-service:3001
      - key: CONTACTS_SERVICE_URL
        value: http://contacts-service:3002
      - key: NOTIFICATIONS_SERVICE_URL
        value: http://notifications-service:3003

  # AUTH SERVICE
  - type: pserv
    name: auth-service
    runtime: docker
    repo: https://github.com/margazm/notifications
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: apps/auth/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-bd
          property: connectionString

  # CONTACTS SERVICE
  - type: pserv
    name: contacts-service
    runtime: docker
    repo: https://github.com/margazm/notifications
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: apps/contacts/Dockerfile
    envVars:
      - key: PORT
        value: 3002
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-bd
          property: connectionString

  # NOTIFICATIONS SERVICE
  - type: pserv
    name: notifications-service
    runtime: docker
    repo: https://github.com/margazm/notifications
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: apps/notifications/Dockerfile
    envVars:
      - key: PORT
        value: 3003
      - fromGroup: shared-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-bd
          property: connectionString
databases:
  - name: notifications-bd
    plan: free
    region: oregon

envVarGroups:
  - name: shared-secrets
