services:
  # API GATEWAY
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: backend/apps/api-gateway/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: GITHUB_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AUTH_SERVICE_URL
        value: http://auth-service:3001
      - key: CONTACTS_SERVICE_URL
        value: http://contacts-service:3002
      - key: NOTIFICATIONS_SERVICE_URL
        value: http://notifications-service:3003

  # AUTH SERVICE
  - type: web
    name: auth-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: backend/apps/auth/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: GITHUB_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

  # CONTACTS SERVICE
  - type: web
    name: contacts-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: backend/apps/contacts/Dockerfile
    envVars:
      - key: PORT
        value: 3002
      - key: GITHUB_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

  # NOTIFICATIONS SERVICE
  - type: web
    name: notifications-service
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: backend/apps/notifications/Dockerfile
    envVars:
      - key: PORT
        value: 3003
      - key: GITHUB_TOKEN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_SERVICE_ID
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_SYSTEM_EMAIL_ADDRESS
        sync: false
      - key: SENDGRID_BASE_TEMPLATE_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: notifications-db
          property: connectionString

databases:
  - name: notifications-db
    plan: free
    region: oregon
